# Control which branches get CI triggers (defaults to all branches if this parameter is not set)
trigger:
- master
- rel/*

# Specify the target branches for pull request builds
pr:
- master
- rel/*

jobs:
- template: azure-windows-pipeline.yml